### ISSUE TITLE
Design a custom set of chess pieces called Pixel

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#228]
What does the word "pixel" bring to mind?

Unleash your imagination! 

A new set of chess pieces needs to be designed as per the following convention.

- Create a folder named `pixel` in `src/assets/img/pieces`.
- Add six pieces for White in `src/assets/img/pieces/pixel`: 
  - `wBishop.svg`
  - `wKing.svg`
  - `wKnight.svg` 
  - `wPawn.svg`
  - `wQueen.svg`
  - `wRook.svg`  
- Add six pieces for Black in `src/assets/img/pieces/pixel`: 
  - `bBishop.svg` 
  - `bKing.svg` 
  - `bKnight.svg` 
  - `bPawn.svg` 
  - `bQueen.svg` 
  - `bRook.svg`
- Files must be in SVG format

In fact, this is the same convention as with the default chess pieces in [`src/assets/img/pieces/default`](https://github.com/chesslablab/redux-chess/tree/master/src/assets/img/pieces/default).

Keep it up, and happy learning and coding.

**Comment by Tathagat27** [comment]
I would like to work on this, Can you please assign this to me .

**Comment by SmashedFrenzy16** [comment]
Hi there, happy learning and coding!

**Comment by CodeMaster7000** [comment]
Hi there, happy learning and coding!

**Comment by SmashedFrenzy16** [comment]
@CodeMaster7000 I think the idea is to custom design chess pieces, as using/ modifying existing ones might run into copyright issues if not properly researched.

**Comment by CodeMaster7000** [comment]
Hi there, happy learning and coding!
