### ISSUE TITLE
Hide the progress bar

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#386]
The progress bar shouldn't be displayed while playing chess with the computer.

![output_trimmed_enhanced](https://user-images.githubusercontent.com/4062000/232451800-0a637dfe-41b2-46ab-9c04-8efadeb796fc.gif)

Keep it up, and happy coding and learning!

**Comment by goutham03062001** [comment]
Hello is this issue still opened? I would love to contribute to this project.

**Comment by programarivm** [comment]
@goutham03062001 welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/redux-chess/blob/master/CONTRIBUTING.md).

Keep it up, and happy coding and learning!

**Comment by programarivm** [comment]
@blaztviper22 welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/redux-chess/blob/master/CONTRIBUTING.md). @goutham03062001 is cheking out this issue at this moment but may need some help. Would you want to be assigned https://github.com/chesslablab/redux-chess/issues/389 instead? 

Keep it up, and happy coding and learning!
