### ISSUE TITLE
Reconnecting functionality missing?

### ISSUE THREAD

**Issue by itsallinyourhead** [chesslablab/react-chess#390]
I can't find a way to continue a game in "Play a friend" mode after connection was lost.
Reloading page leads to a new game.
Reentering invitation code does not work. Seems to work only one time for whatever reason.
First player does not have a invitation code for himself to begin with.

**Comment by programarivm** [comment]
Thank you @itsallinyourhead for raising this issue.

If the connection is lost, at least the opponent is displayed this message: "Your opponent left the game."

![screencapture-chesslablab-2023-04-23-16_14_23](https://user-images.githubusercontent.com/4062000/233845276-dd3ab4f4-d32f-4a5b-b8e4-f0e08933efed.png)

What about displaying a **Reconnect** button to the other player?

**Comment by itsallinyourhead** [comment]
Why not reconnect automatically?

**Comment by programarivm** [comment]
That makes sense. Also the connection may not be established because of reasons that can't be known with certainty. In those cases, it'd be convenient to display an informative message: "The connection was lost and could not be reestablished. Please try again later."

**Comment by programarivm** [comment]
See https://github.com/chesslablab/react-chess/issues/511
