### ISSUE TITLE
Fix the undo of moves

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#395]
Moves need to be undone only if on the current position not while browsing the history. Otherwise an error may occur in the Squares component.

![output_trimmed_enhanced_reduced](https://user-images.githubusercontent.com/4062000/235964275-6eb86ac7-55da-4263-acb6-2657b5373640.gif)

**Comment by Vishesh-Pandey** [comment]
Assign it to me. I can fix it.

**Comment by Vishesh-Pandey** [comment]
Working on it.

**Comment by programarivm** [comment]
This is a hint: 

> The **Undo move** button should be disabled if the board is not displaying the current position, similarly as with playing the computer in [StartedButtonsStockfishMode](https://github.com/chesslablab/react-chess/blob/master/src/features/mode/stockfish/StartedButtonsStockfishMode.js).

Keep it up and happy learning and coding.

**Comment by programarivm** [comment]
Hi @Vishesh-Pandey how is it going?

**Comment by Vishesh-Pandey** [comment]
So I am unable to set up the server correctly in my local system. If I can get help regarding that I may do a lot more things and fix this bug as well. Without the chess server and just running the front end doesn't really allow me to play moves.

**Comment by programarivm** [comment]
Oh, thanks for letting me know. Probably this should be documented. What about setting up the `/etc/hosts` file as described in https://github.com/chesslablab/react-chess/issues/398?
