### ISSUE TITLE
Create a new test with Selenium IDE

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#398]
A new test needs to be recorded in [tests/ChesslaBlab.side](https://github.com/chesslablab/react-chess/blob/master/tests/ChesslaBlab.side) with Selenium IDE.  **Play A73** is intended to play the main line of the Classical Variation in the Benoni Defense: 1.d4 Nf6 2.c4 c5 3.d5 e6 4.Nc3 exd5 5.cxd5 d6 6.e4 g6 7.Nf3 Bg7 8.Be2 O-O 9.O-O. 

**Play C50** is a good example to create **Play A73** as it is shown in the animation below.

![output_trimmed_enhanced_reduced](https://user-images.githubusercontent.com/4062000/236288714-0dfd6711-e96f-4851-b19e-ecd6f250aea3.gif)

Keep it up, and happy learning!

**Comment by sniperadmin** [comment]
Hey @programarivm , Thanks for the invitation, currently I am exploring this error
![image](https://github.com/chesslablab/react-chess/assets/24525973/c57fa033-eb4f-4a57-9106-7e47d05e676b)

**Comment by programarivm** [comment]
It seems as though the following two entries should be added to the `/etc/hosts` file.

```
127.0.0.1       pchess.net
127.0.0.1       nash-dev.local
```

**Comment by programarivm** [comment]
@sniperadmin you may want to setup the `/etc/hosts` file as described next.

```
127.0.0.1       pchess.net
127.0.0.1       www.chesslablab.com
```

This is because of how [chesslablab/react-chess](https://github.com/chesslablab/react-chess) is setup in the `.env.example` file.

```
HOST=www.chesslablab.com
HTTPS=true
PORT=9443
```

![figure-01](https://github.com/chesslablab/react-chess/assets/4062000/3ffa1e03-adbf-4e7a-9384-b29471c08f8d)
**Figure 1**. php cli/wss-server.php

![figure-02](https://github.com/chesslablab/react-chess/assets/4062000/00019920-9f3f-4893-9b87-5e5cfef4385e)
**Figure 2**. npm start

**Comment by programarivm** [comment]
Hi @sniperadmin how is it going?
