### ISSUE TITLE
Add a CAPTCHA field to the Play a Friend dialog 

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#401]
The CAPTCHA field is to make sure that the request to create a correspondence inbox is made by a human and not a bot. 

![screencapture-chesslablab-9443-2023-05-09-18_59_19](https://github.com/chesslablab/react-chess/assets/4062000/d33f5f49-4d83-431c-9992-06db82654c58)
Figure 1. Click on **Correspondence > Play a Friend**.

Keep it up, and happy coding!

**Comment by JIdayyy** [comment]
Hi there, happy learning and coding!

**Comment by SmashedFrenzy16** [comment]
Hi there, happy learning and coding!

**Comment by SmashedFrenzy16** [comment]
Hi @programarivm,

I want to work on this issue. Can you tell me where Play a Friend dialog is located in the organization so that I can attempt to add a CAPTCHA to the dialog?

**Comment by programarivm** [comment]
@JIdayyy and @SmashedFrenzy16, how are things going? 

I'm sorry, just realized it's been a while since this issue was opened. Here's an update.

![screencapture-chesslablab-2023-07-28-13_00_05](https://github.com/chesslablab/react-chess/assets/4062000/34eb0c80-5571-45ab-a8f1-e0cd72a76b86)

**Figure 1**. Click on **Inbox** > **Create Inbox**.

**Correspondence** was renamed to **Inbox** and **Play a Friend** was renamed to **Create Inbox**:

- https://github.com/chesslablab/react-chess/issues/432 

Thus, the CAPTCHA is to be added to the [CreateInboxCodeDialog](https://github.com/chesslablab/react-chess/blob/master/src/features/nav/dialog/CreateInboxCodeDialog.js) component.

Keep it up, and happy learning!
