### ISSUE TITLE
chesslaBlab  website not responsive

### ISSUE THREAD

**Issue by techmannih** [chesslablab/react-chess#430]
hello,

I found an issue in your chesslaBlab website which is not responsive please check it 
And I want to work on this issue ...please assign me of this issue
![2023-06-20-09_52_59-screenshot](https://github.com/chesslablab/react-chess/assets/125847751/1957e33c-ded5-4f8b-b2b4-21eeb5f22652)

**Comment by techmannih** [comment]
work in progress

**Comment by techmannih** [comment]
hello @programarivm

this issue created by your pre tag and its font size  and pre tag 's font going out off container 
can i change its font size different for different screens
please check it 
![2023-06-26-08_46_50-screenshot (1)](https://github.com/chesslablab/react-chess/assets/125847751/d03b3ac8-087a-430a-87ed-5d96e7555b15)

**Comment by programarivm** [comment]
See: 

- https://github.com/chesslablab/react-chess/issues/431
