### ISSUE TITLE
make a navbar in header for the moblie and tablet devices

### ISSUE THREAD

**Issue by techmannih** [chesslablab/react-chess#431]
hello,

I found an issue in your chesslaBlab website which has not a navbar for moblie and tablet devices please check it
And I want to work on this issue ...please assign me of this issue
![2023-06-20-09_52_01-screenshot](https://github.com/chesslablab/react-chess/assets/125847751/c2163201-fe18-400e-a590-b1408cf6c1f5)

**Comment by techmannih** [comment]
work in progress

**Comment by ydv-ankit** [comment]
Have a look at https://github.com/chesslablab/website/blob/master/public/nav.html

**Comment by KelvinHawks** [comment]
Hi there, happy learning and coding!

**Comment by KelvinHawks** [comment]
Hello, you had previously assigned the above task to me but unfortunately
the app failed to run on my machine. The PHP server commands were giving an
error. I want to quit this assignment. Thank you

**Comment by programarivm** [comment]
Thank you all for the comments.

Probably it was not a good idea to publish technical content on chesslablab.com which is a website intended for chess players. The **Blog** option has recently been removed from the main navigation as well as the **Documentation** option.

See:

- https://github.com/chesslablab/chess-api/issues/49
- https://github.com/chesslablab/chess-server/issues/114

Keep it up,
