### ISSUE TITLE
Correpondence and its icon out off there box in chesslaBlab website

### ISSUE THREAD

**Issue by techmannih** [chesslablab/react-chess#432]
hello,

I found an issue in your chesslaBlab website . a correspondence and its icon is outoff from there box  for the small screen devices . please check it
And I want to work on this issue ...please assign me of this issue
![2023-06-20-09_51_01-screenshot](https://github.com/chesslablab/react-chess/assets/125847751/3c5c7138-060c-4d34-82ae-8d924190acb9)

**Comment by programarivm** [comment]
@techmannih welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/react-chess/blob/master/CONTRIBUTING.md).

Keep it up, and happy coding and learning!

**Comment by techmannih** [comment]
work in progress
