### ISSUE TITLE
Rename the text of the buttons

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#437]
"Undo move" should be renamed as "Takeback" in the following buttons:

- [src/features/mode/fen/StartedButtonsFenMode.js](https://github.com/chesslablab/react-chess/blob/master/src/features/mode/fen/StartedButtonsFenMode.js)
- [src/features/mode/pgn/StartedButtonsPgnMode.js](https://github.com/chesslablab/react-chess/blob/master/src/features/mode/pgn/StartedButtonsPgnMode.js)
- [src/features/mode/stockfish/StartedButtonsStockfishMode.js](https://github.com/chesslablab/react-chess/blob/master/src/features/mode/stockfish/StartedButtonsStockfishMode.js)

Happy coding!

**Comment by programarivm** [comment]
@neeravbhaskarla welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/react-chess/blob/master/CONTRIBUTING.md).

Let me just bring up that the PR for this issue should be sent after October 1 because it's been labelled as hacktoberfest.

I can't wait to see what you come up with!

**Comment by programarivm** [comment]
Well this one has been assigned already @neeravbhaskarla, would you want to solve https://github.com/chesslablab/react-chess/issues/438 instead? If so, please comment on the issue: "Hi there, happy learning and coding!"

**Comment by techmannih** [comment]
Sure , I will renamed

**Comment by techmannih** [comment]
Sure , I will be rename

**Comment by programarivm** [comment]
Let me just point out the following for future PRs:

- [Linking a pull request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

**Comment by neeravbhaskarla** [comment]
> "Undo move" should be renamed as "Takeback" in the following buttons:
> 
> * [src/features/mode/fen/StartedButtonsFenMode.js](https://github.com/chesslablab/react-chess/blob/master/src/features/mode/fen/StartedButtonsFenMode.js)
> * [src/features/mode/pgn/StartedButtonsPgnMode.js](https://github.com/chesslablab/react-chess/blob/master/src/features/mode/pgn/StartedButtonsPgnMode.js)
> * [src/features/mode/stockfish/StartedButtonsStockfishMode.js](https://github.com/chesslablab/react-chess/blob/master/src/features/mode/stockfish/StartedButtonsStockfishMode.js)
> 
> Happy coding!

The following files cannot be found, can you please check the paths.

**Comment by programarivm** [comment]
Thank you @neeravbhaskarla and @techmannih for pointing this out.

These are the buttons after the update:

- [src/features/panel/fen/StartedButtons.js](https://github.com/chesslablab/react-chess/blob/master/src/features/panel/fen/StartedButtons.js)

- [src/features/panel/san/StartedButtons.js](https://github.com/chesslablab/react-chess/blob/master/src/features/panel/san/StartedButtons.js)

- [src/features/panel/stockfish/StartedButtons.js](https://github.com/chesslablab/react-chess/blob/master/src/features/panel/stockfish/StockfishPanel.js)

Happy learning and coding!

**Comment by neeravbhaskarla** [comment]
Hi @programarivm, I think I have been assigned to this issue, can I do PR for this issue.
