### ISSUE TITLE
Remove informative message

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#438]
It is self-explanatory that the user is creating an inbox with the purpose to share the code with a friend.

![screencapture-chesslablab-9443-2023-06-26-17_25_44](https://github.com/chesslablab/react-chess/assets/4062000/c2621c50-ee5c-43e8-83c4-40f67ff1e963)
Figure 1. **Create Inbox**

![screencapture-chesslablab-9443-2023-06-26-17_36_21](https://github.com/chesslablab/react-chess/assets/4062000/28b83039-a06b-4b98-9ae7-bed8b23bc2fd)
Figure 2. **Copy Inbox Code**

Thus, the alert containing the info message in the [CreateInboxCodeDialog](https://github.com/chesslablab/react-chess/blob/master/src/features/nav/dialog/CreateInboxCodeDialog.js) component can be removed: "Create a correspondence inbox and share the code with a friend."

Happy coding and learning!

**Comment by neeravbhaskarla** [comment]
Hi there, happy learning and coding!
