### ISSUE TITLE
Use the spread operator to conditionally create the settings object

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#448]
In JavaScript, it is a quite common thing to conditionally add key-value pairs to objects. This can be done using `if` statements as in the `handleCreateCode()` method in the [CreateInviteCodeDialog](https://github.com/chesslablab/react-chess/blob/master/src/features/mode/play/dialog/CreateInviteCodeDialog.js) component. However, the spread operator allows to do the exact same thing sometimes a little less verbosely.

The spread operator should be used in the `handleCreateCode()` method to create the `settings` object similarly as in the [LoadRavDialog](https://github.com/chesslablab/react-chess/blob/master/src/features/mode/rav/dialog/LoadRavDialog.js) component.

See:
- https://github.com/chesslablab/react-chess/issues/447

Keep it up, and happy learning!

**Comment by neeravbhaskarla** [comment]
Can I get this issue assigned?

**Comment by neeravbhaskarla** [comment]
@programarivm can I get this issue assigned?

**Comment by neeravbhaskarla** [comment]
Hi there, happy learning and coding!

**Comment by neeravbhaskarla** [comment]
Submitted PR please check
