### ISSUE TITLE
Pawn Endgame sometimes unplayable

### ISSUE THREAD

**Issue by SmashedFrenzy16** [chesslablab/react-chess#468]
This issue seems to no longer happen or present a problem and is closed now. Previous screenshots sent were the wrong ones, but now, testing the website again, the issue no longer happens.

**Comment by CodeMaster7000** [comment]
If it is white's move just push the pawn to promote. If it is black's move it is an automatic draw of insufficient material.

**Comment by SmashedFrenzy16** [comment]
Sorry, I gave the wrong example @CodeMaster7000. I shall update it with the correct one

**Comment by CodeMaster7000** [comment]
Joe

**Comment by CodeMaster7000** [comment]
@SmashedFrenzy16 Could you please update us now?

**Comment by SmashedFrenzy16** [comment]
@CodeMaster7000 and @programarivm I have updated the issue.

**Comment by SmashedFrenzy16** [comment]
By the way, it is black's go, so the pawn will be gone.

**Comment by CodeMaster7000** [comment]
No... you can play Kg4 and create a path for the pawn to go.

Generally, I have looked through these and they are all playable so this issue should be closed @SmashedFrenzy16

**Comment by SmashedFrenzy16** [comment]
@CodeMaster7000, you are wrong. There is an issue with this. I have updated the issue. Before, I kept posting the wrong image.

**Comment by CodeMaster7000** [comment]
No... you can play Kg4 and create a path for the pawn to go.

Generally, I have looked through these and they are all playable so this issue should be closed @SmashedFrenzy16

**Comment by SmashedFrenzy16** [comment]
@CodeMaster7000 and @programarivm, the issue has been updated. The cases can sometimes be rare (but also frequent).

**Comment by SmashedFrenzy16** [comment]
@CodeMaster7000 and @programarivm, I thik the issue has been solved. Therefore I feel like this issue should be closed now.
