### ISSUE TITLE
Game Heuristics incorrect

### ISSUE THREAD

**Issue by CodeMaster7000** [chesslablab/react-chess#472]
The game heuristics of an endgame all show as 0.00, even if the position is winning for white in several aspects.

![Screenshot 2023-07-31 153648](https://github.com/chesslablab/react-chess/assets/95772109/c722a23f-bca6-475e-9c08-ba3f566fd931)

In this position, white is obviously ahead in material, king safety etc. - but the game heuristics are showing otherwise:

![Screenshot 2023-07-31 153924](https://github.com/chesslablab/react-chess/assets/95772109/1c43da90-918a-49e3-af7e-b2916c2ea5bb)

Can we have some people look into improving this feature?

Best regards,
CodeMaster7000

**Comment by CodeMaster7000** [comment]
This issue appears to be resolved now. It was most likely a temporary glitch.

**Comment by programarivm** [comment]
See:
- https://github.com/chesslablab/chess-server/issues/118
