### ISSUE TITLE
Remove parentheses from the return statement in App

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#473]
Parentheses can be removed from the return statement in [src/App.js](https://github.com/chesslablab/react-chess/blob/master/src/App.js).

**Comment by ANSHADCK** [comment]
I understand the issue and am interested in working on it. can you please assign the issue to me?

**Comment by programarivm** [comment]
@ANSHADCK welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/react-chess/blob/master/CONTRIBUTING.md).

I can't wait to see what you come up with!

**Comment by programarivm** [comment]
😅 I just asked this question on the Reactiflux community, and it turns out that wrapping JSX into parentheses is the right thing to do precisely to avoid automatic semicolon insertion (ASI).

> We split JSX over multiple lines for readability. While it isn’t required, when doing this, we also recommend wrapping it in parentheses to avoid the pitfalls of automatic semicolon insertion.

Introducing JSX. (2023, July 31). https://legacy.reactjs.org/docs/introducing-jsx.html
