### ISSUE TITLE
Remove parentheses from the return statements in the panel folder

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#477]
Parentheses can be removed from the return statements in all functional components in [src/features/panel](https://github.com/chesslablab/react-chess/tree/master/src/features/panel).

- [Buttons.js](https://github.com/chesslablab/react-chess/blob/master/src/features/panel/Buttons.js)
- [ButtonsDialogs.js](https://github.com/chesslablab/react-chess/blob/master/src/features/panel/ButtonsDialogs.js)
- [History.js](https://github.com/chesslablab/react-chess/blob/master/src/features/panel/History.js)
- [MovesTable.js](https://github.com/chesslablab/react-chess/blob/master/src/features/panel/MovesTable.js)
- [OpeningTable.js](https://github.com/chesslablab/react-chess/blob/master/src/features/panel/OpeningTable.js)
- [Panel.js](https://github.com/chesslablab/react-chess/blob/master/src/features/panel/Panel.js)

Keep it up, and happy learning!

**Comment by SmashedFrenzy16** [comment]
@programarivm, here is a fix to the issue (please request changes if I have made an error anywhere): https://github.com/chesslablab/react-chess/pull/480
