### ISSUE TITLE
Remove parentheses from the return statements in the nav/dialog folder

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#478]
Parentheses can be removed from the return statements in all functional components in [src/features/nav/dialog](https://github.com/chesslablab/react-chess/tree/master/src/features/nav/dialog).

**Comment by SmashedFrenzy16** [comment]
@programarivm, I have attempted to solve this issue in the following PR (please request any changes if I have made any errors):https://github.com/chesslablab/react-chess/pull/481
