### ISSUE TITLE
Underpromotion not allowed

### ISSUE THREAD

**Issue by CodeMaster7000** [chesslablab/react-chess#486]
When a pawn reaches the end, it can only become a Queen; however, in chess you can promote to a bishop, knight, or rook. Therefore, can we please have underpromotion allowed in ChesslaBlab?

**Comment by programarivm** [comment]
![Screenshot 2023-08-02 13:09:16](https://github.com/chesslablab/react-chess/assets/4062000/c4ae1a1e-6230-4476-9bc1-d28fc2a399ed)

**Comment by programarivm** [comment]
See https://github.com/chesslablab/php-chess/issues/339
