### ISSUE TITLE
Add sounds

### ISSUE THREAD

**Issue by CodeMaster7000** [chesslablab/react-chess#499]
To make the game more beginner-friendly, having "capture" and "check" sounds may be useful so one would realise when a piece of theirs has been taken, or their King has been checked, etc.

**Comment by real-coder007Ravi** [comment]
I want to work on this issue as I am currently Learning React. Could you please assign it to me??

**Comment by t-trafer** [comment]
Hey @real-coder007Ravi / @programarivm, i would like to take this up if there's no planned activity with it

**Comment by programarivm** [comment]
@t-trafer welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/react-chess/blob/master/CONTRIBUTING.md).

The issue has been updated. Let's focus on adding sounds only.

Happy coding!
