### ISSUE TITLE
Add arrows

### ISSUE THREAD

**Issue by CodeMaster7000** [chesslablab/react-chess#513]
It would be helpful to add the ability to draw arrows. This would help to illustrate future ideas on the chessboard, such as checks, captures, threats, and attacks.

**Comment by adisuyash** [comment]
Yes it's a good idea.

**Comment by matt-d-webb** [comment]
@CodeMaster7000 it would be good if you could share your approach? 

- What would be the MVP of this feature? 
- What, if any, dependencies would you need to introduce? 

As other board implementations have a fair common set of instructional options, it would perhaps make sense to align to a similar standard.

The **Lichess** project [Chessground](https://github.com/lichess-org/chessground) have implemented theirs as follows:

https://github.com/lichess-org/chessground/blob/master/src/draw.ts

Pay particular attention to the keyboard & mouse events used to initiate the drawing:
```js
e.shiftKey
e.ctrlKey
isRightButton(e); //  isRightButton = (e: cg.MouchEvent): boolean => e.buttons === 2 || e.button === 2;
```

Happy to help define the scope and review the PR(s).

**Comment by CodeMaster7000** [comment]
@matt-d-webb 

I would need to take another look into it as for now I had submitted the issue as more of a general feature request.

**Comment by t-trafer** [comment]
would be happy to take this up if you'd like @CodeMaster7000

**Comment by CodeMaster7000** [comment]
Sure! Thank You!
