### ISSUE TITLE
Use the grabbing cursor for when a chess piece is being dragged

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#515]
See:

- https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

Happy coding!

**Comment by DenysLins** [comment]
Hey @programarivm, can I work on that?

**Comment by adisuyash** [comment]
Hey are you still working on this issue @DenysLins ?

**Comment by DenysLins** [comment]
The same for me... I used the docker-compose and tried to run locally without docker, but I'm unable to connect to the socket. I followed all steps in the README from the tree repos: API, server and  front. Do you guys have more detailed instructions?

**Comment by programarivm** [comment]
Thanks for the questions @DenysLins and @adisuyash. 

This issue in particular doesn't require Docker, only the Chess Server up and running. It can be started manually:

```text
php cli/wss-server.php
```

But yes, at this moment there is no staging environment set up.

See: 

- https://github.com/chesslablab/chess-api/issues/60

Keep it up, and happy coding and learning.

**Comment by programarivm** [comment]
See https://github.com/orgs/chesslablab/discussions/350

**Comment by VaibhavKambar7** [comment]
hey can i work on this?

**Comment by programarivm** [comment]
@VaibhavKambar7 welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/react-chess/blob/master/CONTRIBUTING.md).

I can't wait to see what you come up with!

**Comment by apikmeister** [comment]
Hi, i would like to contribute to this issue, but i seems to have issue for the ws to be connected. Can anyone assist me? I use docker to run both server and api.
![Screenshot 2023-10-14 at 11 22 39 PM](https://github.com/chesslablab/react-chess/assets/92358212/fb125713-a1bf-4f58-b544-5521b741516d)

**Comment by programarivm** [comment]
@apikmeister welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/react-chess/blob/master/CONTRIBUTING.md).

Happy coding!

**Comment by programarivm** [comment]
👋 Hello @apikmeister, 

Is this the same issue reported by @zakiyousufi at https://github.com/chesslablab/react-chess/issues/656?

BTW, at this moment `pchess.net` is a staging environment accepting connections from any origin so there's no need to use Docker.

See:

- [The staging environment is up and running](https://github.com/orgs/chesslablab/discussions/357)

Happy learning!
