### ISSUE TITLE
Add more difficulty levels and rating estimates for them

### ISSUE THREAD

**Issue by CodeMaster7000** [chesslablab/react-chess#527]
When playing against different difficulty levels in "Play vs computer", I think it would be a good enhancement to add more of them, since 0-3 may not be a wide enough range to judge your playing ability.

In addition, we could also add rating estimates for the different difficulty levels (these could be in line with FIDE or USCF ratings, for example).

**Comment by SmashedFrenzy16** [comment]
@CodeMaster7000 great idea. We also might want to add different names to the computer difficulty bots to make it more fun.

**Comment by CodeMaster7000** [comment]
Thanks! But I appreciate that it is a lot of work so it may take a while to complete.
