### ISSUE TITLE
Add player rating

### ISSUE THREAD

**Issue by SmashedFrenzy16** [chesslablab/react-chess#528]
Based on online chess games played on ChesslaBlab, users should have a rating (possibly using the ELO system). Then on online games they should be paired with people with similar ratings to them.

**Comment by CodeMaster7000** [comment]
@SmashedFrenzy16 Once again, I think having an elo system attached to players would require games to be stored against their name, which is a mild form of tracking them. So far it seems like ChesslaBlab has avoided this route due to its main focus.

**Comment by SmashedFrenzy16** [comment]
@CodeMaster7000 it could be an auto generated (that does not go through the organisation) rating that the player could choose who can see their data. chesslaBlab would not be able to see the data.

**Comment by programarivm** [comment]
See https://github.com/chesslablab/react-chess/issues/529
