### ISSUE TITLE
Enhancement: Add a variety of puzzles/tactics

### ISSUE THREAD

**Issue by CodeMaster7000** [chesslablab/react-chess#531]
Linking to #487 which involves adding more endgames, perhaps adding tactical puzzles from famous historical games would help to improve players' board vision. With practice, they would then be able to spot sequences leading to checkmate/material gain, improving their in-game performance.

**Comment by programarivm** [comment]
Thanks @CodeMaster7000 for raising this issue!

This one is still perhaps too generic, what about opening a discussion instead?

Right now the link below is the closest thing to adding puzzles in more specific terms.

- https://github.com/chesslablab/chess-api/issues/73

Keep it up,

**Comment by CodeMaster7000** [comment]
@programarivm I have opened https://github.com/orgs/chesslablab/discussions/348, so this feature can be worked on there.
