### ISSUE TITLE
Add light and dark mode 

### ISSUE THREAD

**Issue by Akshat111111** [chesslablab/react-chess#533]

**Comment by Sky-De** [comment]
@programarivm hi, i would like to work on this issue, please assign this to me
Thanks

**Comment by programarivm** [comment]
@Sky-De welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/react-chess/blob/master/CONTRIBUTING.md).

Keep it up, and happy learning and coding!

**Comment by programarivm** [comment]
Thank you @Sky-De,

Can you share details about the error? Terminal messages, console errors as well as screenshots will be helpful.

BTW, as pointed out in [this discussion](https://github.com/orgs/chesslablab/discussions/350) a basic ChesslaBlab environment requires two repos up and running: [React Chess](https://github.com/chesslablab/react-chess) and [PHP Chess Server](https://github.com/chesslablab/chess-server).

Keep it up, and happy coding and learning!

**Comment by JhndaCoder** [comment]
Hi I would like to take up this issue @Sky-De @programarivm

**Comment by programarivm** [comment]
@dev0614 welcome to ChesslaBlab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/react-chess/blob/master/CONTRIBUTING.md).

Happy learning!

**Comment by Akshat111111** [comment]
Feel free to ask anything @dev0614

**Comment by Arturas1989** [comment]
"Hi there, happy learning and coding!"
I would like to help. Can you please assign this to me. Also can I use Tailwind CSS for this ?

**Comment by programarivm** [comment]
@Arturas1989 welcome to ChesslaBlab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/react-chess/blob/master/CONTRIBUTING.md).

Happy learning!

**Comment by programarivm** [comment]
It'd be convenient to stick with MUI for the sake of simplicity.

**Comment by Arturas1989** [comment]
Thank you for assigning me to this. I will start it as soon as possible.

**Comment by programarivm** [comment]
Feel free to ask anything @Arturas1989,

This issue may be quite challenging because a full-stack environment needs to be setup in order to be solved, however, that's not the case with the [chesslablab/reactblab](https://github.com/chesslablab/reactblab) repo. If you like chess and React, please let us know if you'd want to contribute to chesslablab/reactblab instead.

Happy learning!

**Comment by Arturas1989** [comment]
@programarivm To set up dark mode, you need a full-stack environment ? Why ?

**Comment by programarivm** [comment]
Well, not necessarily, it depends on the issue to be solved.

The React Chess app is connected to a WebSocket chess server as well as to an API:

- [How to run React Chess](https://github.com/chesslablab/react-chess/blob/master/CONTRIBUTING.md#how-to-run-react-chess)

**Comment by programarivm** [comment]
At some point there used to be a staging server and frontend contributors would not set up an entire full-stack environment to solve React Chess issues, but it had a cost and was eventually removed. Now it's probably not too obvious to solve some issues.

See https://github.com/chesslablab/react-chess/issues/687

**Comment by Arturas1989** [comment]
Hello. Can someone explain me why I'm getting this error and how to fix it? The files are there in ssl folder.

![image](https://github.com/chesslablab/react-chess/assets/76004308/39e9508c-1d14-4d91-95d5-0e05399032c9)

**Comment by programarivm** [comment]
As per the docs at [Installation](https://chess-server.docs.chesslablab.org/installation/#run-the-chess-server):

> Before starting the secure WebSocket server for the first time, make sure to have created the fullchain.pem and privkey.pem files in the ssl folder.

![Screenshot 2024-02-08 09:46:15](https://github.com/chesslablab/react-chess/assets/4062000/f0c845f5-65b6-429d-9cfb-dc9e8f6f4b1f)

Most probably this is to do with how the SSL certificate has been created, and by the way [certbot](https://certbot.eff.org/instructions) can be used to create the two `.pem` files for these domain names: 

- `chesslablab.org`
- `www.chesslablab.org` 
- `api.chesslablab.org` 
- `async.chesslablab.org`
- `ui.chesslablab.org`

**Comment by Arturas1989** [comment]
Thank you, I will try it
