### ISSUE TITLE
Remove info alert

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#537]
![www chesslablab com_](https://github.com/chesslablab/react-chess/assets/4062000/3ffbd736-ab10-4670-b950-8c2747f53b3e)
**Figure 1**. Click on **Inbox > Read Inbox** and enter an inbox code.

The info alert in the [EnterInboxCodeDialog](https://github.com/chesslablab/react-chess/blob/master/src/features/nav/dialog/EnterInboxCodeDialog.js) component can be removed in favor of a frequently asqued question in the [chesslablab/website](https://github.com/chesslablab/website) repo.

> 🛈 Both players can send a move to the shared correspondence inbox. Whose turn is it now to play?

Keep it up,

**Comment by Abhi1234-tech** [comment]
@programarivm I've opened PR for above Bug , Please check and let me know
