### ISSUE TITLE
White screen when playing

### ISSUE THREAD

**Issue by markmendozadev** [chesslablab/react-chess#538]
Hi, I encountered a white screen when I played.
![image](https://github.com/chesslablab/react-chess/assets/57791540/1f1eaf3e-9676-4114-8afb-cd416feb0f83)

Some error on console:
![image](https://github.com/chesslablab/react-chess/assets/57791540/1a591567-bf20-4e67-a94a-72a7e808aeb9)

**Comment by programarivm** [comment]
@markmendozadev welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/react-chess/blob/master/CONTRIBUTING.md).

Keep it up, and happy learning and coding!

**Comment by programarivm** [comment]
Thank you for raising this issue!

🪳 What are the steps to reproduce the error?

🐜 It seems as though a recent update introduced a bug.

**Comment by markmendozadev** [comment]
@programarivm Hi, I've just played the game that's it. tried 2 games. different positions and the same outcome. So it's really hard to give you the steps because I don't remember anymore.
