### ISSUE TITLE
In-game chat

### ISSUE THREAD

**Issue by CodeMaster7000** [chesslablab/react-chess#542]
Consider adding an in-game chat room for players to talk in during the game. They could talk under the names of [White] and [Black] for their to be no need of storing usernames.

**Comment by SmashedFrenzy16** [comment]
This could be further enhanced by the potential blockchain for ChesslaBlab accounts, which allows for usernames (if the user wants) to be displayed whilst chatting.

**Comment by programarivm** [comment]
Thanks @CodeMaster7000 for raising this issue!

This one is still perhaps too generic, what about opening a discussion instead?

Keep it up,

**Comment by CodeMaster7000** [comment]
@programarivm Done.
