### ISSUE TITLE
Scroll the HTML table of chess moves to the bottom

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#543]
The HTML table in [src/features/panel/MovesTable.js](https://github.com/chesslablab/react-chess/blob/master/src/features/panel/MovesTable.js) should automatically scroll to the bottom while playing to always get the last move displayed.

![figure_01](https://github.com/chesslablab/react-chess/assets/4062000/a3107858-e06c-479d-81a7-7ab29bd009a0)
**Figure 1**. The last move is not being displayed.

![figure_02](https://github.com/chesslablab/react-chess/assets/4062000/a042d7ee-c166-4832-928a-c8762d2df6da)
**Figure 2**. Scroll the table to the bottom to get the last move displayed.

Keep it up and happy learning!

**Comment by shrishail735** [comment]
I want to solve this issue. However, I am facing issues in the setup. Where can I find the /etc/hosts file as mentioned in readme?

**Comment by programarivm** [comment]
@shrishail735 welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/react-chess/blob/master/CONTRIBUTING.md).

Also it'd be helpful if you could open a Q&A [discussion](https://github.com/orgs/chesslablab/discussions) to share the specific issues like error messages and screenshots you're facing with the setup.

Keep it up, and happy learning!
