### ISSUE TITLE
Display a hamburger menu

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#546]
The main menu should be displayed as a hamburger menu on mobile devices.

- Analysis Board
- Play
- Opening Search
- Database
- Training
- Inbox
- Settings

![figure_01](https://github.com/chesslablab/react-chess/assets/4062000/693bb9e3-ec6f-44cb-bacc-2078ffac896d)
**Figure 1**. Display a hamburger menu.

Keep it up, and happy coding and learning!

**Comment by VenusTokyo** [comment]
Hello, Can I work on this?

**Comment by programarivm** [comment]
@VenusTokyo welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/react-chess/blob/master/CONTRIBUTING.md).

Keep it up, and happy learning and coding!
