### ISSUE TITLE
Create the OpeningSearch navigation subcomponent

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#553]
See:

- https://github.com/chesslablab/react-chess/issues/550

Keep it up, and happy learning!

**Comment by vladutvoicu** [comment]
Hello! I would like to work on this issue. I have a question though, I saw that there are multiple issues of creating subcomponents, is it ok for me to work on more than one of these issues?

**Comment by programarivm** [comment]
@vladutvoicu welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/react-chess/blob/master/CONTRIBUTING.md).

Keep it up, and happy learning and coding!
