### ISSUE TITLE
Game crashing whilst in progress

### ISSUE THREAD

**Issue by CodeMaster7000** [chesslablab/react-chess#564]
After playing 6 or 7 moves of a chess game against a computer, it displays the error message below:

![Error](https://github.com/chesslablab/react-chess/assets/95772109/8ffda698-356d-4a97-819f-6175bd19b17d)

The game subsequently crashes and aborts.

Is there any resolution to this error?

**Comment by programarivm** [comment]
It seems as though a recent update introduced a bug. What are the steps to reproduce the error?

**Comment by CodeMaster7000** [comment]
@programarivm I simply went onto the ChesslaBlab website, played a computer, and after 6 moves the game went unresponsive for a few seconds before loading the error.

Could this issue be labelled with bug?

**Comment by programarivm** [comment]
See https://github.com/chesslablab/react-chess/issues/568
