### ISSUE TITLE
Rename the submenu components

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#576]
Rename the submenus in the [src/features/nav/Nav.js](https://github.com/chesslablab/react-chess/blob/master/src/features/nav/Nav.js) component as it is described next.

- AnalysisBoardMenu
- PlayMenu
- OpeningSearchMenu
- DatabaseMenu
- TrainingMenu
- InboxMenu
- SettingsMenu

Happy coding!

**Comment by Tharuneshwarv** [comment]
@programarivm Can you Assign it to me

**Comment by corners2wall** [comment]
Closes in [pr](https://github.com/chesslablab/react-chess/pull/577)

**Comment by programarivm** [comment]
@corners2wall welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/react-chess/blob/master/CONTRIBUTING.md).

Keep it up, and happy learning and coding!

**Comment by programarivm** [comment]
@Tharuneshwarv welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/react-chess/blob/master/CONTRIBUTING.md).

Keep it up, and happy learning and coding!
