### ISSUE TITLE
From Selenium IDE to JavaScript Mocha

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#585]
A collection of Selenium automated tests has been created in [tests/ChesslaBlab.side](https://github.com/chesslablab/react-chess/blob/master/tests/ChesslaBlab.side) using the [Selenium IDE](https://chrome.google.com/webstore/detail/selenium-ide/mooikfkahbdckldjjndioackbalphokd) Chrome Extension as it is shown in the example below.

![output_trimmed_enhanced_reduced](https://github.com/chesslablab/react-chess/assets/4062000/77310411-fd41-494d-a5bd-cbec376293a9)
**Figure 1**. **Play A73** is run with Selenium IDE.

These tests can be created quite easily, and are helpful as long as you're in front of the screen checking out everything is working as expected. They can also be automated.

Selenium IDE can't export to [Jest](https://jestjs.io/) format which is the JavaScript testing framework being used by React Chess.

See:

- [Supported Exports](https://www.selenium.dev/selenium-ide/docs/en/introduction/code-export#supported-exports)

![figure_02](https://github.com/chesslablab/react-chess/assets/4062000/c2c22373-470f-4d21-acd9-e663057f79c6)

**Figure 2**. Explort **Play A73**

However, the tests can be exported as JavaScript Mocha which is quite similar to Jest. At this stage we'll be using the Selenium IDE Chrome extension to export each and every test in the [tests/ChesslaBlab.side](https://github.com/chesslablab/react-chess/blob/master/tests/ChesslaBlab.side) file to JavaScript Mocha. The exports will be stored in the [tests/mocha](https://github.com/chesslablab/react-chess/tree/master/tests/mocha) folder.

- [x] https://github.com/chesslablab/react-chess/issues/586
- [x] https://github.com/chesslablab/react-chess/issues/587
- [x] https://github.com/chesslablab/react-chess/issues/588
- [x] https://github.com/chesslablab/react-chess/issues/589
- [x] https://github.com/chesslablab/react-chess/issues/590
- [x] https://github.com/chesslablab/react-chess/issues/591
- [x] https://github.com/chesslablab/react-chess/issues/609

Happy learning!

**Comment by dotarjun** [comment]
Hey. Pls assign me

**Comment by programarivm** [comment]
@dotarjun this is a collection of 7 tasks.
