### ISSUE TITLE
Export "Play C20 and load the PGN movetext" to JavaScript Mocha

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#588]
Export the **Play C20 and load the PGN movetext** test to JavaScript Mocha using the Selenium IDE Chrome extension.

Keep it up,

**Comment by dotarjun** [comment]
Pls assign

**Comment by joshl26** [comment]
I am an avid coder and would like to take on this issue!

**Comment by joshl26** [comment]
#642 Complete
