### ISSUE TITLE
Export "Search A08 and continue the game" to JavaScript Mocha

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#590]
Export the **Search A08 and continue the game** test to JavaScript Mocha using the Selenium IDE Chrome extension.

Keep it up,

**Comment by dotarjun** [comment]
Pls assign

**Comment by ayush-chandil** [comment]
Can you assign to me too?

**Comment by programarivm** [comment]
@ayush-chandil welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/react-chess/blob/master/CONTRIBUTING.md).

Happy coding!

**Comment by programarivm** [comment]
@dotarjun the Hacktoberfest challenge consists of hacking out 4 valid Pull Requests.
 
Keep it up, I can't wait to see what you come up with!
