### ISSUE TITLE
Game crashing whilst in progress

### ISSUE THREAD

**Issue by CodeMaster7000** [chesslablab/react-chess#600]
This error has appeared before as explained in #564, and does not seem to have been resolved.

![20230918_202429.png](https://github.com/chesslablab/react-chess/assets/95772109/76b2399e-a404-4121-a024-4f66e3382802)

**Comment by CodeMaster7000** [comment]
@programarivm The previous issue had been closed as completed, so I opened up a new one. Maybe something else has to be done as the previous solution seemed to be only temporary...

**Comment by Mayank2001kh** [comment]
anyone knows why this is happening?

**Comment by CodeMaster7000** [comment]
No idea here but it seems to throw time out errors too

**Comment by Mayank2001kh** [comment]
Hey,
if you are using Nginx server there is default timeout setting which timeout websocket connection after 60 secons so to solve this you need to reconfigure your nginx server proxy and change/add below things

- proxy_connect_timeout – maximum time to connect to a proxied server (default 60, usually under 75)
- proxy_read_timeout – maximum time (between reads) to read proxied server response (default 60)

**Comment by CodeMaster7000** [comment]
It would be true but that's not the cause of the error. The problem I am facing is that I disconnect while still on the servers and playing a game.

**Comment by programarivm** [comment]
Well, at this moment the chesslablab.com site is running on a staging server which may contain errors.

It'd be nice if the bugs could be replicated.

See:

- https://github.com/chesslablab/react-chess/issues/651

Also the testing issues will help.

- https://github.com/chesslablab/react-chess/issues/615

Keep it up,

**Comment by programarivm** [comment]
@CodeMaster7000 how many times out of 10 attempts would the error appear? If it is rather frequent but cannot be replicated, there's no problem, please attach the exact time when it happens. The sequence of commands in [the log](https://github.com/chesslablab/chess-server/tree/master/storage) can be inspected.

**Comment by CodeMaster7000** [comment]
@programarivm Aren't these empty files?

**Comment by programarivm** [comment]
For the sake of security, the `storage/pchess.log` file exists in the staging environment only not in the GitHub repo which is a shared environment.

> You can create a .gitignore file in your repository's root directory to tell Git which files and directories to ignore when you make a commit. To share the ignore rules with other users who clone the repository, commit the .gitignore file in to your repository.

See:

- [Ignoring files](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files)

Happy coding!

**Comment by CodeMaster7000** [comment]
@programarivm The issue also occurred at a similar frequency to the reconnecting issue, at a few times out of 10.

**Comment by programarivm** [comment]
@CodeMaster7000 may I ask what device are you using when the error occurs?

See https://github.com/chesslablab/react-chess/issues/678

**Comment by CodeMaster7000** [comment]
Yes it is indeed often on a mobile.
