### ISSUE TITLE
Vertical Scrollbar is coming up which should not show

### ISSUE THREAD

**Issue by Faisalhs51** [chesslablab/react-chess#601]
The Scrollbar is been shown in the computer view which is due to the "footer".
The footer is not containing anything.

![image](https://github.com/chesslablab/react-chess/assets/89152237/f2ef43b2-48df-48fd-9367-e7e1b2ae237d)

**Comment by programarivm** [comment]
The [website](https://github.com/chesslablab/website) repo is an example of how the React Chess repo can be forked and extended. At this moment there's no footer defined.
