### ISSUE TITLE
Add a file upload input field

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#614]
![www chesslablab com_](https://github.com/chesslablab/react-chess/assets/4062000/f55ce692-13d4-4557-aba7-d10b3a87bcce)
Click on **Analysis Board > Import Image**. 

This message is being displayed: "Soon available, please be patient!" A file upload input field needs to be added to the dialog. The message will be displayed once the user has selected a file of any of the following formats: PNG, JPG, GIF. No more programming is required to close this issue — just add a new file upload input field, it's a really good first issue to get familiar with the codebase.

See:

- https://github.com/chesslablab/chess-api/issues/81

Keep it up!

**Comment by Mithilesh-create** [comment]
Working on this issue.

**Comment by programarivm** [comment]
@Mithilesh-create welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/react-chess/blob/master/CONTRIBUTING.md).

Keep it up, and happy learning and coding!

**Comment by Mithilesh-create** [comment]
![image](https://github.com/chesslablab/react-chess/assets/68504882/6dd6054e-2ee2-405f-af54-3e1c423e2c29)

**Comment by Mithilesh-create** [comment]
Added Input file functionality and created pull request.
