### ISSUE TITLE
From JavaScript Mocha to Jest

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#615]
After exporting the Selenium IDE tests to JavaScript Mocha and once Selenium WebDriver has been set up, let's transcribe each and every test in the [tests/mocha](https://github.com/chesslablab/react-chess/tree/master/tests/mocha) folder into Jest in the [automated](https://github.com/chesslablab/react-chess/tree/master/src/__tests__/automated) folder.

- [x] https://github.com/chesslablab/react-chess/issues/621
- [x] https://github.com/chesslablab/react-chess/issues/616
- [x] https://github.com/chesslablab/react-chess/issues/617
- [x] https://github.com/chesslablab/react-chess/issues/618
- [x] https://github.com/chesslablab/react-chess/issues/619
- [x] https://github.com/chesslablab/react-chess/issues/620
- [x] https://github.com/chesslablab/react-chess/issues/622

Happy coding!

**Comment by dotarjun** [comment]
I'd start this after #585.

**Comment by programarivm** [comment]
@dotarjun this is a collection of tasks.

**Comment by SmashedFrenzy16** [comment]
@programarivm issue fixed here: https://github.com/chesslablab/react-chess/pull/634
