### ISSUE TITLE
Transcribe "Play A73" to Jest

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#616]
Transcribe the **Play A73** test to Jest.

Happy coding,

**Comment by ShatilKhan** [comment]
Please assign me. I've done some jest test contributions before

**Comment by programarivm** [comment]
@ShatilKhan welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/react-chess/blob/master/CONTRIBUTING.md).

Keep it up, and happy learning and coding!
