### ISSUE TITLE
Transcribe "Play C20 and load the PGN movetext" to Jest

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#617]
Transcribe the **Play C20 and load the PGN movetext** test to Jest.

Happy coding,

**Comment by Labhk** [comment]
I'd like to work on this

**Comment by programarivm** [comment]
@Labhk welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/react-chess/blob/master/CONTRIBUTING.md).

Keep it up, and happy learning and coding!
