### ISSUE TITLE
Transcribe "Undo castling in a Fischer Random game" to Jest

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#620]
Transcribe the **Undo castling in a Fischer Random game** test to Jest.

Happy coding,

**Comment by programarivm** [comment]
@ChiragAgg5k welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/react-chess/blob/master/CONTRIBUTING.md).

Keep it up, and happy learning and coding!

**Comment by ChiragAgg5k** [comment]
@programarivm i had a small doubt, in which directory should i add this test?
