### ISSUE TITLE
Transcribe "En passant capture and promote" to Jest

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#621]
Transcribe the **En passant capture and promote** test to Jest.

Happy coding,

**Comment by tusharagrawalgeek** [comment]
Hey @programarivm  I'm a 1000 rated chess player on chess.com as well as a react developer. I believe I can fix this issue with ease. Kindly assign it to me.

**Comment by programarivm** [comment]
@tusharagrawalgeek welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/react-chess/blob/master/CONTRIBUTING.md).

Let me just point out that the PR for this issue should be sent from October 1 because it's been labelled as hacktoberfest.

Also the following issue should be solved first:

- https://github.com/chesslablab/react-chess/issues/592

See:

- [Automated tests with Selenium WebDriver and Jest](https://github.com/chesslablab/react-chess/milestone/1)

Keep it up, and happy learning and coding!
