### ISSUE TITLE
Transcribe "Castling in a Fischer Random game" to Jest

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#622]
Transcribe the **Castling in a Fischer Random game** test to Jest.

Happy coding,

**Comment by dotarjun** [comment]
Hey, I'd like to work on this

**Comment by programarivm** [comment]
@dotarjun welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/react-chess/blob/master/CONTRIBUTING.md).

Let me just point out that the PR for this issue should be sent from October 1 because it's been labelled as hacktoberfest.

Also the following issue should be solved first:

- https://github.com/chesslablab/react-chess/issues/592

See:

- [Automated tests with Selenium WebDriver and Jest](https://github.com/chesslablab/react-chess/milestone/1)

Keep it up, and happy learning and coding!

**Comment by ayush-chandil** [comment]
Can you assign me this issue?
