### ISSUE TITLE
Fix CAPTCHA

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#627]
See https://github.com/chesslablab/chess-api/issues/120

**Comment by SmashedFrenzy16** [comment]
@programarivm where is the CAPTCHA located?

**Comment by programarivm** [comment]
It's the [src/features/Captcha.js](https://github.com/chesslablab/react-chess/blob/master/src/features/Captcha.js) component.

**Comment by SmashedFrenzy16** [comment]
@programarivm PR to fix this issue: https://github.com/chesslablab/react-chess/pull/636

Please suggest any changes I need to make.
