### ISSUE TITLE
Unstyled "Connect to IRC" form

### ISSUE THREAD

**Issue by kuv2707** [chesslablab/react-chess#659]
The form appears to be unstyled as compared to the rest of the site.

**Comment by programarivm** [comment]
Gamja is an embedded `iframe` hosted by [Libera.Chat](https://libera.chat/) which is currently being used as described in the [Guides](https://libera.chat/guides/webchat#gamja). Not too sure about how to customize the CSS styles, it seems as if GitHub issues can't be opened on the [Libera-Chat/gamja](https://github.com/Libera-Chat/gamja) repo.

**Comment by programarivm** [comment]
Hi 👋 @glguy, @tomaw, @Freso, @stwalkerster, @ilbelkyr, @mquin, @mniip, @AbstractBeliefs, @aaronmdjones, @ncoevoet, @TheDaemoness, @joseeantonior, @benharri, @swantzter, @jesopo, @A-UNDERSCORE-D

Thank you for the amazing work on the webchat IRC clients!

1. Can we open GitHub issues on the [Libera-Chat](https://github.com/Libera-Chat) repos?
2. How can we customize the CSS styles in the Gamja iframe?

Keep it up,

**Comment by AbstractBeliefs** [comment]
You can open issues on first party projects we run.

For changes to gamja, please go upstream to https://sr.ht/~emersion/gamja/
, where the project is run.

In general, if you can not ping every staff member in unrelated repos, that
is appreciated at well.

**Comment by programarivm** [comment]
Thank you @AbstractBeliefs for sharing a link to the bug tracker.

It'd be awesome if GitHub users could ask and document questions about using the IRC clients.

Keep it up,

**Comment by AbstractBeliefs** [comment]
You can, but only on our first party projects.

We don't have any control over how gamja is developed so you should tell
the upstream developers what you want to happen, there is little we can do
in this instance.
