### ISSUE TITLE
De-hardcode the HTTPS scheme to access the API URLs

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#697]
The HTTPS scheme is being hardcoded throughout the code to access the API URLs as shown in the following example.

```
`https://${process.env.REACT_APP_API_HOST}:${process.env.REACT_APP_API_PORT}/api/autocomplete/event`
```

A new variable called `REACT_APP_API_SCHEME` needs to be created in the `.env.example` and `.env` files. Then, the API calls need to be updated accordingly.

```
`${process.env.REACT_APP_API_SCHEME}://${process.env.REACT_APP_API_HOST}:${process.env.REACT_APP_API_PORT}/api/autocomplete/event`
```

Happy coding and learning!

**Comment by VTPrince** [comment]
Hi there, happy learning and coding!
@programarivm i'd love to work on this issue, could you assign it to me?

**Comment by programarivm** [comment]
@VTPrince welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/react-chess/blob/master/CONTRIBUTING.md).

Happy learning!
