### ISSUE TITLE
Add a new game action called Explain Position

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#699]
A new list item called **Explain Position** needs to be added to the **Game Action** list implemented in the [src/features/panel/Buttons.js](https://github.com/chesslablab/react-chess/blob/master/src/features/panel/Buttons.js) component. 

![Screenshot 2024-01-12 19:07:53](https://github.com/chesslablab/react-chess/assets/4062000/07143f29-d590-429e-a463-bb376ea3bdc9)
**Figure 1**. The **Game Actions** list is located on the right side of the screen.

The following MUI icon will be used since **Explain Position** is intended to explain the current position.

```
import CommentIcon from '@mui/icons-material/Comment';
```

No additional programming is required to close this issue — just display the list item, it's a really good first issue to get familiar with the codebase!

Keep it up, and happy coding.

**Comment by Luzefiru** [comment]
Hi there, happy learning and coding!

**Comment by programarivm** [comment]
@Luzefiru welcome to ChesslaBlab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/react-chess/blob/master/CONTRIBUTING.md).

Happy learning!
